### ISSUE TITLE
Poor Error when using Pivnet Resources

### ISSUE THREAD

**Issue by Oskoss** [pivotal-cf/pivnet-resource#84]
When using the PCF-Pipelines to deploy PCF 1.12 on AWS with concourse I hit the following error:

```
2017/12/28 21:50:08 PivNet Resource version: 0.31.5
2017/12/28 21:50:08 Creating download directory: /tmp/build/get
2017/12/28 21:50:08 Getting release for product slug: 'elastic-runtime' and product version: '1.12.9'
2017/12/28 21:50:08 Accepting EULA for release with ID: 9710
2017/12/28 21:50:08 Getting product files
2017/12/28 21:50:08 Getting file groups
2017/12/28 21:50:10 Getting release dependencies
2017/12/28 21:50:11 Getting dependency specifiers
2017/12/28 21:50:11 Getting release upgrade paths
2017/12/28 21:50:12 Getting upgrade path specifiers
2017/12/28 21:50:12 Downloading files
2017/12/28 21:50:12 Filtering download links by glob
2017/12/28 21:50:12 Downloading filtered files
2017/12/28 21:50:12 Downloading: 'PCF Elastic Runtime' to file: '/tmp/build/get/cf-1.12.9-build.3.pivotal'
 2.44 GiB / 8.01 GiB [=============>-----------------------------]  30.44% 1m17spanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x62e2bc]

goroutine 122 [running]:
github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/download.Client.retryableRequest(0x848fa0, 0xc420079410, 0x849e20, 0xc42006a958, 0x84e180, 0xc42050b4a0, 0x84b120, 0xc4200e2520, 0xc420546240, 0x235, ...)
    /tmp/build/80754af9/gopath/src/github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/download/downloader.go:165 +0x27c
github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/download.Client.Get.func1(0x7572742d00000008, 0x70a688)
    /tmp/build/80754af9/gopath/src/github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/download/downloader.go:93 +0xb3
github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc42025ce80, 0xc420147b00)
    /tmp/build/80754af9/gopath/src/github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/vendor/golang.org/x/sync/errgroup.(*Group).Go
    /tmp/build/80754af9/gopath/src/github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
```
I did end up getting around the error by sizing up the ephemeral disk size on the concourse worker nodes, but it would be helpful for a better error rather than a seg fault.

**Comment by Oskoss** [comment]
@robdimsdale Had some great ideas why this was happening such as checking the status of a type assertion. Feel free to add more!

**Comment by robdimsdale** [comment]
I noticed that https://github.com/pivotal-cf/pivnet-resource/blob/master/vendor/github.com/pivotal-cf/go-pivnet/download/downloader.go#L164 isn't checking the outcome of the type assertion of the error, which could lead to nil pointers a couple of lines below.

Given that providing more disk resolved the issue, it's not clear that there is any underlying issue that needs to be fixed beyond a more helpful error message.

**Comment by jimbosity** [comment]
Thanks - we made a story to update our error messaging - currently in our icebox: https://www.pivotaltracker.com/story/show/153961305

**Comment by robdimsdale** [comment]
I think the way to fix this is to check that the type assertion succeeded, and if not, exit with error (i.e. go straight to https://github.com/pivotal-cf/pivnet-resource/blob/master/vendor/github.com/pivotal-cf/go-pivnet/download/downloader.go#L169, and don't attempt to do any string comparison on: https://github.com/pivotal-cf/pivnet-resource/blob/master/vendor/github.com/pivotal-cf/go-pivnet/download/downloader.go#L165).
